  function observableCatchHandler(source, handler) ***REMOVED***
    return new AnonymousObservable(function (observer) ***REMOVED***
      var d1 = new SingleAssignmentDisposable(), subscription = new SerialDisposable();
      subscription.setDisposable(d1);
      d1.setDisposable(source.subscribe(observer.onNext.bind(observer), function (exception) ***REMOVED***
        var d, result;
        try ***REMOVED***
          result = handler(exception);
        ***REMOVED*** catch (ex) ***REMOVED***
          observer.onError(ex);
          return;
        ***REMOVED***
        isPromise(result) && (result = observableFromPromise(result));

        d = new SingleAssignmentDisposable();
        subscription.setDisposable(d);
        d.setDisposable(result.subscribe(observer));
      ***REMOVED***, observer.onCompleted.bind(observer)));

      return subscription;
    ***REMOVED***, source);
  ***REMOVED***

  /**
   * Continues an observable sequence that is terminated by an exception with the next observable sequence.
   * @example
   * 1 - xs.catchException(ys)
   * 2 - xs.catchException(function (ex) ***REMOVED*** return ys(ex); ***REMOVED***)
   * @param ***REMOVED***Mixed***REMOVED*** handlerOrSecond Exception handler function that returns an observable sequence given the error that occurred in the first sequence, or a second observable sequence used to produce results when an error occurred in the first sequence.
   * @returns ***REMOVED***Observable***REMOVED*** An observable sequence containing the first sequence's elements, followed by the elements of the handler sequence in case an exception occurred.
   */
  observableProto['catch'] = observableProto.catchError = function (handlerOrSecond) ***REMOVED***
    return typeof handlerOrSecond === 'function' ?
      observableCatchHandler(this, handlerOrSecond) :
      observableCatch([this, handlerOrSecond]);
  ***REMOVED***;

  /**
   * @deprecated use #catch or #catchError instead.
   */
  observableProto.catchException = function (handlerOrSecond) ***REMOVED***
    //deprecate('catchException', 'catch or catchError');
    return this.catchError(handlerOrSecond);
  ***REMOVED***;
